// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type ArchivesDocumentDataSlicesSlice = never

/**
 * Content for archives documents
 */
interface ArchivesDocumentData {
  /**
   * Title field in *archives*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: archives.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Content field in *archives*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: archives.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField

  /**
   * Slice Zone field in *archives*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: archives.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArchivesDocumentDataSlicesSlice> /**
   * Meta Description field in *archives*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: archives.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *archives*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: archives.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *archives*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: archives.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * archives document from Prismic
 *
 * - **API ID**: `archives`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArchivesDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<ArchivesDocumentData>,
  'archives',
  Lang
>

type HomePageDocumentDataSlicesSlice = BasicContentSlice | ProjectListingSlice

/**
 * Content for home page documents
 */
interface HomePageDocumentData {
  /**
   * Title field in *home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * content field in *home page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField

  /**
   * Media field in *home page*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.media
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  media: prismic.LinkToMediaField

  /**
   * Slice Zone field in *home page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Description field in *home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *home page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<HomePageDocumentData>,
  'home_page',
  Lang
>

/**
 * Item in *Menu → Links*
 */
export interface MenuDocumentDataLinksItem {
  /**
   * Label field in *Menu → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Document field in *Menu → Links*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.links[].document
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  document: prismic.ContentRelationshipField
}

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Content field in *Menu*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField

  /**
   * Links field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<MenuDocumentDataLinksItem>>
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<MenuDocumentData>,
  'menu',
  Lang
>

type PageDocumentDataSlicesSlice = BasicContentSlice | ProjectListingSlice | HeroHeaderSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Type field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: page.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<'Default' | 'Home' | 'About' | 'Archives' | 'Project listing', 'filled'>

  /**
   * Content field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<PageDocumentData>,
  'page',
  Lang
>

/**
 * Item in *Project → Contents*
 */
export interface ProjectDocumentDataContentsItem {
  /**
   * Title field in *Project → Contents*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.contents[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Content field in *Project → Contents*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.contents[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

type ProjectDocumentDataSlicesSlice = never

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Status field in *Project*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Published
   * - **API ID Path**: project.status
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  status: prismic.SelectField<'Published' | 'Archived', 'filled'>

  /**
   * Excerpt field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField

  /**
   * Content field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField

  /**
   * Main media field in *Project*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project.main_media
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  main_media: prismic.LinkToMediaField

  /**
   * Creation field in *Project*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: project.creation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  creation: prismic.DateField

  /**
   * Contents field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.contents[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contents: prismic.GroupField<Simplify<ProjectDocumentDataContentsItem>>

  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<ProjectDocumentData>,
  'project',
  Lang
>

type ProjectListingDocumentDataSlicesSlice = never

/**
 * Content for project listing documents
 */
interface ProjectListingDocumentData {
  /**
   * Title field in *project listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Content field in *project listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField

  /**
   * Slice Zone field in *project listing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectListingDocumentDataSlicesSlice> /**
   * Meta Description field in *project listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project_listing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *project listing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *project listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project_listing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField /**
   * Header title field in *project listing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.header_title
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_title: prismic.KeyTextField

  /**
   * Header content field in *project listing*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.header_content
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header_content: prismic.RichTextField
}

/**
 * project listing document from Prismic
 *
 * - **API ID**: `project_listing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectListingDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<ProjectListingDocumentData>,
  'project_listing',
  Lang
>

/**
 * Item in *settings → Socials*
 */
export interface SettingsDocumentDataSocialsItem {
  /**
   * Label field in *settings → Socials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Social field in *settings → Socials*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].social
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  social: prismic.SelectField<'Facebook' | 'Instagram' | 'Behance' | 'Linkedin' | 'Viméo' | 'Youtube'>
}

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
  /**
   * App title field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.app_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  app_title: prismic.KeyTextField

  /**
   * App description field in *settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.app_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  app_description: prismic.RichTextField

  /**
   * Email field in *settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField

  /**
   * Socials field in *settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<Simplify<SettingsDocumentDataSocialsItem>>
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<SettingsDocumentData>,
  'settings',
  Lang
>

export type AllDocumentTypes =
  | ArchivesDocument
  | HomePageDocument
  | MenuDocument
  | PageDocument
  | ProjectDocument
  | ProjectListingDocument
  | SettingsDocument

/**
 * Primary content in *BasicContent → Primary*
 */
export interface BasicContentSliceDefaultPrimary {
  /**
   * Title field in *BasicContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_content.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Excerpt field in *BasicContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_content.primary.excerpt
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField

  /**
   * Link field in *BasicContent → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_content.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * Link label field in *BasicContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_content.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  link_label: prismic.RichTextField

  /**
   * Media field in *BasicContent → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: basic_content.primary.media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  media: prismic.LinkToMediaField
}

/**
 * Default variation for BasicContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BasicContentSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<BasicContentSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *BasicContent*
 */
type BasicContentSliceVariation = BasicContentSliceDefault

/**
 * BasicContent Shared Slice
 *
 * - **API ID**: `basic_content`
 * - **Description**: BasicContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BasicContentSlice = prismic.SharedSlice<'basic_content', BasicContentSliceVariation>

/**
 * Primary content in *HeroHeader → Primary*
 */
export interface HeroHeaderSliceDefaultPrimary {
  /**
   * Title field in *HeroHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_header.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Content field in *HeroHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_header.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField

  /**
   * Media field in *HeroHeader → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_header.primary.media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  media: prismic.LinkToMediaField
}

/**
 * Default variation for HeroHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHeaderSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroHeaderSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *HeroHeader*
 */
type HeroHeaderSliceVariation = HeroHeaderSliceDefault

/**
 * HeroHeader Shared Slice
 *
 * - **API ID**: `hero_header`
 * - **Description**: HeroHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHeaderSlice = prismic.SharedSlice<'hero_header', HeroHeaderSliceVariation>

/**
 * Primary content in *ProjectListing → Primary*
 */
export interface ProjectListingSliceDefaultPrimary {
  /**
   * Title field in *ProjectListing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Excerpt field in *ProjectListing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.primary.excerpt
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField

  /**
   * Link field in *ProjectListing → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * Link label field in *ProjectListing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField
}

/**
 * Primary content in *ProjectListing → Items*
 */
export interface ProjectListingSliceDefaultItem {
  /**
   * Projet field in *ProjectListing → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.items[].projet
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  projet: prismic.ContentRelationshipField<'project'>
}

/**
 * Default variation for ProjectListing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectListingSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ProjectListingSliceDefaultPrimary>,
  Simplify<ProjectListingSliceDefaultItem>
>

/**
 * Slice variation for *ProjectListing*
 */
type ProjectListingSliceVariation = ProjectListingSliceDefault

/**
 * ProjectListing Shared Slice
 *
 * - **API ID**: `project_listing`
 * - **Description**: ProjectListing
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectListingSlice = prismic.SharedSlice<'project_listing', ProjectListingSliceVariation>

declare module '@prismicio/client' {
  interface CreateClient {
    (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      ArchivesDocument,
      ArchivesDocumentData,
      ArchivesDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataContentsItem,
      ProjectDocumentDataSlicesSlice,
      ProjectListingDocument,
      ProjectListingDocumentData,
      ProjectListingDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSocialsItem,
      AllDocumentTypes,
      BasicContentSlice,
      BasicContentSliceDefaultPrimary,
      BasicContentSliceVariation,
      BasicContentSliceDefault,
      HeroHeaderSlice,
      HeroHeaderSliceDefaultPrimary,
      HeroHeaderSliceVariation,
      HeroHeaderSliceDefault,
      ProjectListingSlice,
      ProjectListingSliceDefaultPrimary,
      ProjectListingSliceDefaultItem,
      ProjectListingSliceVariation,
      ProjectListingSliceDefault,
    }
  }
}
