// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
    basic_content: defineAsyncComponent(
        () => import("./BasicContent/index.vue"),
    ),
    hero_header: defineAsyncComponent(() => import("./HeroHeader/index.vue")),
    project_listing: defineAsyncComponent(
        () => import("./ProjectListing/index.vue"),
    ),
});
